name: clf
channels:
  - pytorch
  - defaults
dependencies:
  - asn1crypto=1.2.0
  - blas=1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.4
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.4.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.17.4
  - numpy-base=1.17.4
  - openssl=1.1.1d
  - pandas=0.25.3
  - pip=19.3.1
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.7.5
  - python-dateutil=2.8.1
  - pytorch=1.3.1
  - pytz=2019.3
  - readline=7.0
  - requests=2.22.0
  - setuptools=42.0.2
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.8
  - urllib3=1.25.7
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11

